# Это файл запуска процесса на stage
version: "3"

services:

  app:
    build: .
    volumes:
      - ./src/.:/app/.
      - ./log:/tmp/log
      - ./tests/.:/tests
    env_file:  .env-stage

    #command: bash -c "pip freeze"

    #command: bash -c "python -m pytest /tests/* --log-cli-level=INFO"
    #command: bash -c "python -m pytest /tests/main/test* --log-cli-level=INFO"
    #command: bash -c "python -m pytest /tests/gitlab/test* --log-cli-level=INFO"
    #command: bash -c "python -m pytest /tests/oracle/test* --log-cli-level=INFO"
    command: bash -c "python -m pytest /tests/service/test_popers.py --log-cli-level=INFO"
    #command: bash -c "python -m pytest /tests/main/test_call.py --log-cli-level=INFO"
