---
name: PyTest

on:

  workflow_run:
    workflows: ["Test, lint, release, deploy"]
    branches: [ master ]
    types: [completed]
  # push:
  #   branches:
  #     - main
  #     - master
  #   paths-ignore:
  #   - '.github/workflows/*'

jobs:
  tests:
      name: pytest tests
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        env:
          PYTHONPATH: "./src"
        run: |
          pip install pytest
          cd src
          python -m pytest ../tests/main/test* --log-cli-level=INFO
