---
name: PyTest

on:
  workflow_dispatch:

jobs:
  tests:
      name: pytest tests
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        env: 
          PYTHONPATH: "./app"
        run: |
          pip install pytest
          python -m pytest ./tests/main/test*
