name: Release

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - master
  #   paths-ignore:
  #   - '.github/workflows/*'
  workflow_run:
    workflows: ["Lint-flake8", "PyTest"]
    types: [completed]
jobs:

  on-failure-release:
    name: Release failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: failure
      run: echo failure release workflow
    
  on-success-release:

    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        id: wait-for-build-test
        with:
          ref: master
          check-name: 'pytest tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Wait for lint to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        id: wait-for-build-lint
        with:
          ref: master
          check-name: 'Lint flake8'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@5.0.0
            conventional-changelog-eslint@3.0.9
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
